//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptimizePrime
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantStudy
    {
        public int ApplicantStudiesID { get; set; }
        public string StudiesDescription { get; set; }
        public string StudiesLocation { get; set; }
        public string StudiesDuration { get; set; }
        public int ApplicantID { get; set; }
    
        public virtual Applicant Applicant { get; set; }
    }
}
